PREFIX ub: <http://lubm.franz.com#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX u0d0: <http://www.Department0.University0.edu/> 

#		SELECT DISTINCT ?X ?Y
		SELECT ?X ?Y
		WHERE {
		u0d0:AssociateProfessor0	ub:teacherOf ?Y . 
		?Y rdf:type ub:Course . 
		?X ub:takesCourse ?Y . 
		?X rdf:type ub:Student . 
		}
