PREFIX ub: <http://lubm.franz.com#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX u0d0: <http://www.Department0.University0.edu/> 
#SELECT DISTINCT ?X ?Y ?Z
SELECT ?X ?Y ?Z
WHERE {
?Y ub:subOrganizationOf <http://www.University0.edu> . 
?Y rdf:type ub:Department . 
?X ub:memberOf ?Y . 
?X rdf:type ub:Student . 
?X ub:emailAddress ?Z . 
}
