PREFIX dc: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX game: <http://tw.rpi.edu/2011/security-game#>
SELECT ?id ?start ?end WHERE {
    ?event rdf:type game:Event .
    ?event dc:identifier ?id .
    ?event game:startTime ?start .
    ?event game:endTime ?end .
}
