PREFIX dc: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX game: <http://tw.rpi.edu/2011/security-game#>
SELECT ?id ?type ?name ?casualties WHERE {
    ?target rdf:type ?t .
    ?t rdfs:label ?type .
    ?target dc:identifier ?id .
    ?target foaf:name ?name .
    ?target game:potentialCasualties ?casualties .
}
