PREFIX ub: <http://lubm.franz.com#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX u0d0: <http://www.Department0.University0.edu/> 
#SELECT DISTINCT ?X ?Y ?Z
SELECT ?X ?Y ?Z
WHERE {
?Z rdf:type ub:Department . 
?Z ub:subOrganizationOf ?Y . 
?X ub:undergraduateDegreeFrom ?Y . 
?X ub:memberOf ?Z . 
?X rdf:type ub:GraduateStudent . 
?Y rdf:type ub:University . 
}
