# a query for handoff interactions in which I am the giver

PREFIX activity: <http://fortytwo.net/2015/extendo/activity#>

# note: replace <I> before evaluation
SELECT ?thing ?other ?otherName WHERE {
    ?h activity:thingGiven ?thing .
    ?h activity:giver <I> .
    ?h activity:taker ?other .
    ?h foaf:name ?otherName .
}