# a query for attentional feedback on point gestures

PREFIX activity: <http://fortytwo.net/2015/extendo/activity#>

# note: replace <I> before evaluation
SELECT ?person ?focus WHERE {
    # <I> have pointed at ?focus (at any time)
    ?p activity:actor <I> .
    ?p activity:thingIndicated ?focus .

    # ?person has paid attention to ?focus (at any time)
    ?a activity:actor ?person .
    ?a activity:focusOfAttention ?focus .
}
