# a query for handshake interactions in which I am one of the participants,
# and the other participant and I both know a particular person

PREFIX activity: <http://fortytwo.net/2015/extendo/activity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

# note: replace <I> before evaluation
SELECT ?person ?acquaintance WHERE {
    ?h a activity:Handshake .
    ?h activity:actor <I> .
    ?h activity:actor ?person .
    <I> foaf:knows ?acquaintance .
    ?person foaf:knows ?acquaintance .
}