# a query for handoff interactions in which I am the taker

PREFIX activity: <http://fortytwo.net/2015/extendo/activity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

# note: replace <I> before evaluation
SELECT ?thing ?other ?otherName WHERE {
    ?h activity:thingGiven ?thing .
    ?h activity:taker <I> .
    ?h activity:giver ?other .
    ?other foaf:name ?otherName .
}