# a query for objects another actor has pointed to which have a topic of interest to me

PREFIX activity: <http://fortytwo.net/2015/extendo/activity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

# note: replace <I> before evaluation
SELECT ?actor ?indicated ?topic WHERE {
    ?a activity:actor ?actor .
    ?a activity:thingIndicated ?indicated .
    ?indicated foaf:topic ?topic .
    <I> foaf:interest ?topic .
}
