# a query for objects another actor has pointed to which are of interest to me

PREFIX activity: <http://fortytwo.net/2015/extendo/activity#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# note: replace <I> before evaluation
SELECT ?actor ?indicated ?topic ?name WHERE {
    ?a activity:actor ?actor .
    ?a activity:thingIndicated ?indicated .
    <I> foaf:interest ?indicated .
    ?indicated rdfs:label ?name .  # TODO: some things have foaf:name instead of rdfs:label
    FILTER(?actor != <I>)
}
